"""Spring callback schemas for analysis results - Updated for Spring Boot compatibility.

Includes all data categories that Spring Boot expects:
- Characters, Events, Settings, Relationships
- Consistency Report, Validation
"""
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field

# Removed: from app.schemas.plot import PlotResult
from app.schemas.consistency import ConsistencyReport
from app.schemas.validation import ValidationResult


class AnalysisMetadata(BaseModel):
    """Metadata about the analysis execution."""
    processing_time_ms: int = Field(default=0, description="Total processing time in milliseconds")
    tokens_used: int = Field(default=0, description="Total tokens consumed")
    trace_id: Optional[str] = Field(None, description="Distributed tracing ID")
    agents_executed: list[str] = Field(
        default_factory=list, 
        description="List of executed agent names"
    )


class FullAnalysisResult(BaseModel):
    """Complete analysis result structure - Spring Boot compatible.
    
    All fields match the expected schema in Spring Boot's AICallbackService.
    """
    # Level 1 Extraction Results (Synced to Neo4j directly)
    # Removed: characters, events, settings, relationships
    
    # Level 2 Analysis Results
    # Removed: plot
    consistency_report: dict[str, Any] = Field(default_factory=dict)
    validation: dict[str, Any] = Field(default_factory=dict)
    
    # Document Summary (for Spring Backend storage)
    document_summary: Optional[str] = Field(
        None, 
        description="Chapter/document summary generated by AI"
    )
    
    # Character Timeline Tracking (for Spring Backend storage)
    character_timelines: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Chapter-level character state snapshots"
    )
    
    # Metadata
    metadata: Optional[AnalysisMetadata] = None


class AnalysisCallbackPayload(BaseModel):
    """Callback payload sent to Spring Boot after analysis completion.
    
    This schema matches the expected format in Spring's AICallbackService.
    """
    job_id: str = Field(..., alias="jobId", description="Job identifier")
    status: Literal["COMPLETED", "WARNING", "FAILED"] = Field(..., description="Analysis status")
    result: Optional[FullAnalysisResult] = Field(default=None, description="Analysis results")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    
    model_config = {
        "populate_by_name": True,
        "json_schema_extra": {
            "example": {
                "jobId": "job-12345",
                "status": "COMPLETED",
                "result": {
                    # Removed: characters, events, settings, relationships
                    "consistency_report": {
                        "overall_score": 95,
                        "conflicts": [],
                        "resolution_summary": {"total_conflicts": 0}
                    },
                    "validation": {
                        "is_valid": True,
                        "quality_score": 98,
                        "action": "approve"
                    },
                    "document_summary": "Chapter 1: The protagonist enters the castle...",
                    "metadata": {
                        "processing_time_ms": 5000,
                        "trace_id": "trace-123",
                        "agents_executed": ["character", "event", "setting"]
                    }
                },
                "error": None
            }
        }
    }
